openapi: 3.1.0
info:
  title: n8n Workflow Library (GitHub-backed)
  description: |
    Read-only API for the fraserbrownirl/n8n-workflow-library repository using GitHub Raw.
    Enables a GPT action to fetch indexes and workflow JSON files directly from the repo.
  version: 1.0.1

servers:
  - url: https://raw.githubusercontent.com/fraserbrownirl/n8n-workflow-library/main
    description: GitHub Raw (serves JSON/JSONL files directly)

paths:
  /indexes/manifest.json:
    get:
      operationId: getManifest
      summary: Get the master manifest
      description: Fetches indexes/manifest.json from the repo.
      responses:
        '200':
          description: Manifest JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Manifest'
        '404':
          description: Not found

  /indexes/categories.json:
    get:
      operationId: getCategories
      summary: Get category index
      description: Fetches indexes/categories.json.
      responses:
        '200':
          description: Categories map
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryIndex'
        '404':
          description: Not found

  /indexes/quality.json:
    get:
      operationId: getQualityScores
      summary: Get quality scores
      description: Fetches indexes/quality.json.
      responses:
        '200':
          description: Quality scores list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QualityScore'
        '404':
          description: Not found

  /indexes/embeddings.jsonl:
    get:
      operationId: getEmbeddingsJsonl
      summary: Get embeddings JSONL
      description: Fetches indexes/embeddings.jsonl for vector-based usage.
      responses:
        '200':
          description: NDJSON with embeddings
          content:
            text/plain:
              schema:
                type: string
                description: One JSON object per line (NDJSON)
        '404':
          description: Not found

  /workflows/{filename}:
    get:
      operationId: getWorkflowByFilename
      summary: Get a specific workflow JSON by filename
      description: Fetches workflows/{filename} from the repo (must include `.json`).
      parameters:
        - name: filename
          in: path
          required: true
          description: Workflow filename, e.g. AI_agent_chat.json
          schema:
            type: string
            pattern: '^.+\.json$'
      responses:
        '200':
          description: The workflow JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '404':
          description: Not found

components:
  schemas:
    Manifest:
      type: object
      properties:
        total_workflows:
          type: integer
        generated_at:
          type: string
          description: ISO 8601 timestamp
        workflows:
          type: array
          items:
            $ref: '#/components/schemas/ManifestEntry'

    ManifestEntry:
      type: object
      properties:
        filename:
          type: string
        name:
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        complexity:
          type: string
          enum: [beginner, intermediate, advanced, unknown]
        quality_score:
          type: number
        node_count:
          type: integer
        apis:
          type: array
          items:
            type: string

    CategoryIndex:
      type: object
      description: Map of category name -> list of workflows in that category
      properties: {}
      additionalProperties:
        type: array
        items:
          type: object
          properties:
            filename:
              type: string
            name:
              type: string
            quality_score:
              type: number

    QualityScore:
      type: object
      properties:
        filename:
          type: string
        name:
          type: string
        quality_score:
          type: number
        complexity:
          type: string
        has_documentation:
          type: boolean
        categories:
          type: array
          items:
            type: string

    Workflow:
      type: object
      description: Raw n8n workflow JSON (shape varies)
      properties:
        nodes:
          type: array
        connections:
          type: object
        _metadata:
          type: object
          properties:
            name:
              type: string
            used_count:
              type: integer
            popularity_score:
              type: number
            source_url:
              type: string
            scraped_at:
              type: string
      additionalProperties: true
